import { IncomingHttpHeaders } from "http";

import vortez from "../../build/Vortez.js";

import TestSuite from "../support/TestSuite/TestSuite.js";
import Duplex from "../support/Duplex.mock.js";
import Request from "../support/Request.mock.js";
import Codec from "../../build/server/websocket/Codec.js";

const suite = new TestSuite('websocket');

export class Websocket {
    /**
     * MockConnection creates a pair of connected duplex streams to simulate client-server communication.
     * The client_duplex represents the client's side of the connection, while the server_duplex represents the server's side.
     * Data written to client_duplex will be readable from server_duplex and vice versa.
     * This is useful for unit testing the WebSocket implementation in isolation, ensuring that the handshake logic works correctly without relying on external factors.
     */
    public static MockDuplexPair(): Websocket.MockDuplexPair {
        const client_duplex = new Duplex();
        const server_duplex = new Duplex();
        client_duplex.connect(server_duplex);
        return { client_duplex, server_duplex };
    }
    /**
     * Creates a pair of WebSocket connections (client and server) using mock duplex streams to simulate the WebSocket handshake process.
     * The function allows for customization of the handshake process through options such as waiting for the open event dispatch, automatically accepting the handshake request, and providing custom duplex pairs or fake URLs.
     * It returns a promise that resolves with the created client and server WebSocket instances once the handshake process is complete and both connections are open.
     * This utility is essential for testing the WebSocket implementation in a controlled environment, allowing for validation of the handshake logic and message exchange without relying on actual network connections.
     * 
     * @param options - An object containing optional parameters to customize the WebSocket pair creation process, including:
     *   - waitOpenDispatch: Whether to wait for the 'open' event to be dispatched before resolving (default is true).
     *   - autoAcceptRequest: Whether to automatically accept the handshake request on the server side (default is true).
     *   - DuplexPair: A custom pair of mock duplex streams to use for simulating the client-server connection (default is generated by MockDuplexPair()).
     *   - FakeUrl: A fake URL to use for the client's handshake request (default is 'ws://localhost:8080').
     * @returns A promise that resolves with an object containing the client and server WebSocket instances once the handshake process is complete and both connections are open.
     * @remarks This function is particularly useful for unit testing the WebSocket handshake process, allowing developers to verify that the client and server correctly handle the handshake and establish a connection without needing to set up actual network communication.
     */
    public static async WebSocketPair(options: Websocket.WebSocketPairOptions = {}): Promise<Websocket.WebSocketPair> {
        const {
            waitOpenDispatch = true,
            autoAcceptRequest = true,
            flushEvents = false,
            DuplexPair = Websocket.MockDuplexPair(),
            FakeUrl = 'ws://localhost:8080'
        } = options
        const { client_duplex, server_duplex } = DuplexPair;

        const request = vortez.WebSocket.Client.parseURL(FakeUrl);

        const receivedRequestPromise = TestSuite.Utils.awaitEvent<Request>((done, fail) => {
            server_duplex.once('data', chunk => {
                const httpRequestString: string = chunk.toString();
                const request = Websocket.parseRequest(Buffer.from(httpRequestString, 'utf-8'));
                done(request);
            });
        }, 1000);

        const client = new vortez.WebSocket.Client(client_duplex, request);
        client.startHandshake();

        const receivedRequest = await receivedRequestPromise;
        const server = new vortez.WebSocket.Server(receivedRequest, server_duplex);

        if (autoAcceptRequest) await server.accept();
        if (!autoAcceptRequest && waitOpenDispatch) throw new Error('Cannot wait for open event dispatch when autoAcceptRequest is false');
        if (!waitOpenDispatch) return { client, server };

        return TestSuite.Utils.awaitEvent<Websocket.WebSocketPair>((done, fail) => {
            let opened = 0;
            const check = () => {
                opened++;
                if (opened === 2) {
                    client.offAllOnce('error');
                    server.offAllOnce('error');
                    done({ client, server });
                }
            };

            client.once('open', check);
            server.once('open', check);
            client.once('error', fail);
            server.once('error', fail);
            
            if (flushEvents) {
                server.flush();
                client.flush();
            }

        }, 500);
    }
    /**
     * Splits a raw HTTP request or Websocket.Response buffer into its header and body components.
     * The function looks for the double CRLF sequence that separates the header from the body. If found, it extracts the header and body accordingly. If not found, it treats the entire buffer as the header and assumes there is no body.
     * This is a crucial step in processing HTTP messages during the WebSocket handshake, allowing the server to correctly interpret the client's request and respond appropriately.
     * @param data - The raw HTTP request or Websocket.Response data as a Buffer.
     * @returns An object containing the header as a Buffer and an optional body as a Buffer if it exists.
     */
    public static getMessageParts(data: Buffer): Websocket.MessageParts {
        let headerEndIndex = data.indexOf('\r\n\r\n');
        let header: Buffer, payload: Buffer;
        if (headerEndIndex === -1) {
            headerEndIndex = data.length;
            payload = Buffer.alloc(0);
        } else {
            payload = data.subarray(headerEndIndex + 4);
        }
        header = data.subarray(0, headerEndIndex);
        return { header, payload };
    }
    /**
     * Parses raw HTTP request or Websocket.Response strings into structured headers and status information.
     * For requests, it extracts the method, path, and headers. For Websocket.Responses, it extracts the HTTP version, status code, status message, and headers.
     * This is essential for validating the WebSocket handshake process, ensuring that the correct headers are present and that the status codes are as expected.
     * The function handles multi-line headers and normalizes header keys to lowercase for easier access.
     * @param header - The raw HTTP request or Websocket.Response header to be parsed.
     * @returns An object containing the parsed method, path, headers for requests, or status and headers for Websocket.Responses.
     */
    public static parseHeaders(header: Buffer): IncomingHttpHeaders {
        const headerString = header.toString('utf-8');

        const headers: IncomingHttpHeaders = {};
        const headerLines = headerString.split('\r\n').slice(1);
        for (const line of headerLines) {
            if (line === '') break;
            if (/^[\t ]/.test(line)) {
                const lastKey = Object.keys(headers).slice(-1)[0];
                if (lastKey) headers[lastKey] += ' ' + line.trim();
            } else {
                const colonIndex = line.indexOf(':');
                const key = line.slice(0, colonIndex).trim().toLowerCase();
                const value = line.slice(colonIndex + 1).trim();
                headers[key] = value;
            }
        }
        return headers;
    }
    /**
     * Parses the body of an HTTP request or Websocket.Response, extracting the payload, its size, and optionally its MIME type.
     * This function is used to handle the payload of WebSocket messages after the handshake process is complete, ensuring that the data is correctly interpreted and processed.
     * It takes into account the possibility of an empty payload and handles it gracefully by returning an empty buffer and a size of zero.
     * The MIME type is extracted from the headers if available, which can be useful for determining how to process the payload (e.g., text vs binary).
     * @param payload - The raw payload data as a Buffer.
     * @param header - Optional HTTP headers that may contain content-type information for determining the MIME type of the payload.
     * @returns An object containing the parsed payload, its size, and optionally its MIME type.
     */
    public static parseBody(payload: Buffer, header?: IncomingHttpHeaders): Request.body {
        if (!payload) return { payload: Buffer.alloc(0), size: 0 };
        const size = payload.length;
        const mimetype = header?.['content-type'];
        return { payload, size, mimetype };
    }
    /**
     * Parses a raw HTTP request string into a structured Request object, extracting the method, path, and headers.
     * This is used to validate the client's handshake request during the WebSocket connection process, ensuring that it contains the necessary headers and uses the correct HTTP method.
     * @param httpRequest - The raw HTTP request string to be parsed.
     * @returns A Request object containing the method, URL path, and headers extracted from the raw HTTP request string.
     */
    public static parseRequest(httpRequest: Buffer): Request {
        const { header, payload } = Websocket.getMessageParts(httpRequest);
        const headers = Websocket.parseHeaders(header);
        const body = Websocket.parseBody(payload, headers);
        const [method, path] = header.toString('utf-8').split('\r\n')[0].split(' ');
        return new Request({ method, url: path, headers, body });
    }
    public static parseResponse(httpResponse: Buffer): Websocket.Response {
        const { header, payload } = Websocket.getMessageParts(httpResponse);
        const headers = Websocket.parseHeaders(header);
        const [version, statusString, ...statusMessageParts] = header.toString('utf-8').split('\r\n')[0].split(' ');
        const statusMessage = statusMessageParts.join(' ');
        const status = parseInt(statusString);
        const body = Websocket.parseBody(payload, headers);
        return { version, status, statusMessage, headers, body };
    }
}
export namespace Websocket {
    export interface MessageParts {
        header: Buffer;
        payload: Buffer;    
    }
    export interface Response {
        version: string;
        status: number;
        statusMessage: string;
        headers: IncomingHttpHeaders; // OutgoingHttpHeaders
        body: Request.body;
    }

    export type MockDuplexPair = {
        client_duplex: Duplex;
        server_duplex: Duplex;
    }

    export type WebSocketPair = {
        client: vortez.WebSocket.Client;
        server: vortez.WebSocket.Server;
    }

    export interface WebSocketPairOptions {
        waitOpenDispatch?: boolean;
        autoAcceptRequest?: boolean;
        flushEvents?: boolean;
        DuplexPair?: MockDuplexPair;
        FakeUrl?: string;
    }
}




suite.add('Testing Websocket Handshake Process.', async (test) => {
    const { client_duplex, server_duplex } = Websocket.MockDuplexPair();

    const requestPromise = test.awaitEvent<Request>((done) => {
        server_duplex.once('data', (data) => {
            test.info('Server received handshake request');
            const request = Websocket.parseRequest(data);
            const { method, url, headers } = request;

            test.expect(method).equals('GET', 'Handshake request should use GET method');
            test.expect(url).equals('/', 'Handshake request should target the correct path');

            test.expect(headers['upgrade'] && headers['upgrade'].toLowerCase() === 'websocket').ok('Handshake request should include Upgrade: websocket header');
            test.expect(headers['connection'] && headers['connection'].toLowerCase().includes('upgrade')).ok('Handshake request should include Connection: Upgrade header');
            test.expect(headers['sec-websocket-key']).ok('Handshake request should include Sec-WebSocket-Key header');
            test.expect(headers['sec-websocket-version'] && headers['sec-websocket-version'] === '13').ok('Handshake request should include Sec-WebSocket-Version: 13 header');
            test.expect(headers['host'] && headers['host'] === 'localhost:8080').ok('Handshake request should include correct Host header');

            done(request);
        });
    });

    client_duplex.once('data', chunk => {
        test.info('Client received handshake Websocket.Response');
        const { version: httpVersion, status: statusCode, statusMessage, headers } = Websocket.parseResponse(chunk);

        test.expect(httpVersion).equals('HTTP/1.1', 'Handshake Websocket.Response should use HTTP/1.1');
        test.expect(statusCode).equals(101, 'Handshake Websocket.Response should have status code 101');
        test.expect(statusMessage).equals('Switching Protocols', 'Handshake Websocket.Response should have status message "Switching Protocols"');

        test.expect(headers['upgrade'] && headers['upgrade'].toLowerCase() === 'websocket').ok('Handshake Websocket.Response should include Upgrade: websocket header');
        test.expect(headers['connection'] && headers['connection'].toLowerCase().includes('upgrade')).ok('Handshake Websocket.Response should include Connection: Upgrade header');
        test.expect(headers['sec-websocket-accept']).ok('Handshake Websocket.Response should include Sec-WebSocket-Accept header');
    });

    const request = vortez.WebSocket.Client.parseURL('ws://localhost:8080');
    const client = new vortez.WebSocket.Client(client_duplex, request);
    client.startHandshake();

    const receivedRequest = await requestPromise;
    const server = new vortez.WebSocket.Server(receivedRequest, server_duplex);

    test.expect(request.path).equals(receivedRequest.url, 'Parsed request should have correct path');
    test.expect(server.status).equals('handshake', 'Server should be in handshake status after receiving handshake request');

    let clientOk = false, serverOk = false, tires = 0;

    return test.awaitEvent<void>((done) => {
        function tryDone() {
            tires += 1;
            if (tires > 2) test.fail('detected multiple open events, something is wrong with the handshake process');
            if (!clientOk || !serverOk) return;
            test.done('Websocket handshake completed successfully');
            done();
        }

        server.on('open', () => {
            test.info('Server connection opened');
            test.expect(server.status).equals('open', 'Server should be in open status after handshake is complete');
            serverOk = true;
            tryDone();
        });
        server.on('close', () => {
            test.expect(server.status).equals('closed', 'Server should be in closed status after connection is closed');
            test.info('Server websocket connection closed');
            test.expect(client.status).equals('closed', 'Client should also be in closed status after server closes the connection');
            clientOk = false;
        });
        server.on('error', (error) => {
            test.done('Server websocket connection error: ' + error.message, error);
        });

        client.on('open', () => {
            test.info('Client connection opened');
            test.expect(client.status).equals('open', 'Client should be in open status after handshake is complete');
            clientOk = true;
            tryDone();
        });
        client.on('close', () => {
            test.expect(client.status).equals('closed', 'Client should be in closed status after connection is closed');
            test.info('Client websocket connection closed');
            clientOk = false;
        });
        client.on('error', (error) => {
            test.done('Client websocket connection error: ' + error.message, error);
        });

        // Flush any buffered events to trigger the handshake process
        // Vortez`s server side routing are automatically call to flush
        // but in client side we need to call it manually after setting up event listeners
        // to ensure that events are emitted and handled correctly during the handshake process.
        // client.flush();
        // server.flush();

       server.accept();
    }, 200);
});

suite.add('Testing websocket message exchange.', async (test) => {
    const { client, server } = await Websocket.WebSocketPair({ waitOpenDispatch: false, autoAcceptRequest: true });

    return test.awaitEvent<void>(async (done) => {
        server.on('open', () => {
            test.info('Server connection opened');
            test.expect(server.status).equals('open', 'Server should be in open status after handshake is complete');
        });
        client.on('open', () => {
            test.info('Client connection opened');
            test.expect(client.status).equals('open', 'Client should be in open status after handshake is complete');
            client.send('Hello Server');
        });
        server.on('message', (message) => {
            test.info('Server received message from client');
            test.expect(server.status).equals('open', 'Server should only receive messages when in open status');
            test.expect(message.isText).ok('Received message should be a text message');
            const payload = message.payload.toString('utf-8');
            test.expect(payload).equals('Hello Server', 'Server should receive the correct message from client');
            server.send('Hello Client');
        });
        client.on('message', (message) => {
            test.info('Client received message from server');
            test.expect(client.status).equals('open', 'Client should only receive messages when in open status');
            test.expect(message.isText).ok('Received message should be a text message');
            const payload = message.payload.toString('utf-8');
            test.expect(payload).equals('Hello Client', 'Client should receive the correct message from server');
            client.close();
        });
        client.on('close', () => {
            test.info('Client websocket connection closed');
            test.expect(client.status).equals('closed', 'Client should be in closed status after connection is closed');
        });
        server.on('close', () => {
            test.info('Server websocket connection closed');
            test.expect(server.status).equals('closed', 'Server should be in closed status after connection is closed');
            test.done('Websocket handshake and communication test completed successfully');
            done();
        });
        server.on('error', (error) => {
            test.done('Server websocket connection error: ' + error.message, error);
            done();
        });
        client.on('error', (error) => {
            test.done('Client websocket connection error: ' + error.message, error);
            done();
        });

        // Flush any buffered events to trigger the handshake process
        // Vortez`s server side routing are automatically call to flush
        // but in client side we need to call it manually after setting up event listeners
        // to ensure that events are emitted and handled correctly during the handshake process.
        // client.flush();
        // server.flush();
    }, 2000);
});

suite.add('Testing fragmented message reassembly.', async (test) => {
    const { client, server } = await Websocket.WebSocketPair();

    return test.awaitEvent<void>(async (done) => {
        server.on('message', (msg) => {
            test.expect(msg.payload.toString()).equals('Fragmented message for testing!', 'Should reassemble fragments');
            test.done('Fragmentation test passed');
            done();
        });
        server.on('error', (error) => {
            test.done('Server websocket connection error: ' + error.message, error);
            done();
        });
        client.on('error', (error) => {
            test.done('Client websocket connection error: ' + error.message, error);
            done();
        });
        const fragments = Codec.clientEncodeFragments(Buffer.from('Fragmented message for testing!'), 0x1, 4);
        for (const index in fragments) {
            const fragment = fragments[index];
            test.info(`Sending fragment ${parseInt(index) + 1}/${fragments.length}`);
            client.connection.write(fragment);
        }
    }, 1000);
});

suite.add('Testing automated Ping/Pong Websocket.Response.', async (test) => {
    const { client, server } = await Websocket.WebSocketPair({ autoAcceptRequest: true });

    return test.awaitEvent<void>(async (done) => {
        server.on('error', (error) => {
            test.done('Server websocket connection error: ' + error.message, error);
            done();
        });
        client.on('error', (error) => {
            test.done('Client websocket connection error: ' + error.message, error);
            done();
        });
        client.on('pong', (data) => {
            test.info('Client received pong from server');
        });
        
        const customPingPromise = new Promise<void>((done) => {
            server.once('ping', (data) => {
                test.info('Server received ping from client');
                const text = data.toString('utf-8');
                test.expect(text).equals('ping with custom data!', 'Ping payload should match the sent data');
                done();
            });
        });

        const data = Buffer.from('ping with custom data!', 'utf-8');
        client.write(data, 0x9);
        await customPingPromise;

        server.once('ping', (data) => {
            test.info('Server received ping from client');
            const text = data.toString('utf-8');
            test.expect(text.length).equals(36, 'Ping payload should be 36 characters long');
        });

        const ping = await client.ping();
        test.info(`Ping round-trip time: ${ping} ms`);
        test.expect(ping < 1000).ok('Ping round-trip time should be less than 1000 ms');
        test.done('Ping/Pong test passed');
        done();
    }, 1000);
});

suite.add('Testing Event Buffering (No message loss).', async (test) => {
    const { client, server } = await Websocket.WebSocketPair();

    client.send('Buffered message 1');
    client.send('Buffered message 2');
    client.send('Buffered message 3');

    return test.awaitEvent<void>(async (done) => {
        let count = 0;

        test.info('Waiting 100ms before attaching listener...');
        await test.sleep(100);

        test.info('Attaching listener now...');
        server.on('message:text', (text) => {
            count++;
            test.info(`Received buffered: ${text}`);
            
            if (count === 3) {
                test.done('Event buffering test passed: All messages recovered');
                done();
            }
        });
        server.flush();
    }, 2000);
});

const result = await suite.run();
process.exit(result ? 0 : 1);